
DROP INDEX IF EXISTS IX_EducationOrganizationEducationOrganizationProgram_EducationOrganizationId ON [eop].[EducationOrganizationEducationOrganizationProgram];
CREATE INDEX IX_EducationOrganizationEducationOrganizationProgram_EducationOrganizationId ON [eop].[EducationOrganizationEducationOrganizationProgram](EducationOrganizationId) INCLUDE (AggregateId);

DROP INDEX IF EXISTS IX_EducationOrganizationProgramProvider_EducationServiceCenterId ON [eop].[EducationOrganizationProgramProvider];
CREATE INDEX IX_EducationOrganizationProgramProvider_EducationServiceCenterId ON [eop].[EducationOrganizationProgramProvider](EducationServiceCenterId) INCLUDE (AggregateId);
