ALTER TABLE edorgprogram.EducationOrganizationEducationOrganizationProgram ADD CONSTRAINT FK_5395cd_EducationOrganization FOREIGN KEY (EducationOrganizationId)
REFERENCES edfi.EducationOrganization (EducationOrganizationId)
;

ALTER TABLE edorgprogram.EducationOrganizationEducationOrganizationProgram ADD CONSTRAINT FK_5395cd_EducationOrganizationProgramProvider FOREIGN KEY (NameOfInstitution)
REFERENCES edorgprogram.EducationOrganizationProgramProvider (NameOfInstitution)
;

CREATE INDEX FK_5395cd_EducationOrganizationProgramProvider
ON edorgprogram.EducationOrganizationEducationOrganizationProgram (NameOfInstitution ASC);

ALTER TABLE edorgprogram.EducationOrganizationEducationOrganizationProgram ADD CONSTRAINT FK_5395cd_EducationOrganizationProgramTypeDescriptor FOREIGN KEY (EducationOrganizationProgramTypeDescriptorId)
REFERENCES edorgprogram.EducationOrganizationProgramTypeDescriptor (EducationOrganizationProgramTypeDescriptorId)
;

CREATE INDEX FK_5395cd_EducationOrganizationProgramTypeDescriptor
ON edorgprogram.EducationOrganizationEducationOrganizationProgram (EducationOrganizationProgramTypeDescriptorId ASC);

ALTER TABLE edorgprogram.EducationOrganizationProgramAuthorizedProvider ADD CONSTRAINT FK_2af181_EducationOrganizationProgramProvider FOREIGN KEY (NameOfInstitution)
REFERENCES edorgprogram.EducationOrganizationProgramProvider (NameOfInstitution)
;

CREATE INDEX FK_2af181_EducationOrganizationProgramProvider
ON edorgprogram.EducationOrganizationProgramAuthorizedProvider (NameOfInstitution ASC);

ALTER TABLE edorgprogram.EducationOrganizationProgramAuthorizedProvider ADD CONSTRAINT FK_2af181_EducationOrganizationProgramTypeDescriptor FOREIGN KEY (EducationOrganizationProgramTypeDescriptorId)
REFERENCES edorgprogram.EducationOrganizationProgramTypeDescriptor (EducationOrganizationProgramTypeDescriptorId)
;

CREATE INDEX FK_2af181_EducationOrganizationProgramTypeDescriptor
ON edorgprogram.EducationOrganizationProgramAuthorizedProvider (EducationOrganizationProgramTypeDescriptorId ASC);

ALTER TABLE edorgprogram.EducationOrganizationProgramProvider ADD CONSTRAINT FK_5934c5_EducationServiceCenter FOREIGN KEY (EducationServiceCenterId)
REFERENCES edfi.EducationServiceCenter (EducationServiceCenterId)
;

ALTER TABLE edorgprogram.EducationOrganizationProgramTypeDescriptor ADD CONSTRAINT FK_cf7f75_Descriptor FOREIGN KEY (EducationOrganizationProgramTypeDescriptorId)
REFERENCES edfi.Descriptor (DescriptorId)
ON DELETE CASCADE
;

