
DROP INDEX IF EXISTS IX_EducationOrganizationEducationOrganizationProgram_EducationOrganizationId;
CREATE INDEX IF NOT EXISTS IX_EducationOrganizationEducationOrganizationProgram_EducationOrganizationId ON edorgprogram.EducationOrganizationEducationOrganizationProgram(EducationOrganizationId) INCLUDE (AggregateId);

DROP INDEX IF EXISTS IX_EducationOrganizationProgramProvider_EducationOrganizationId;
CREATE INDEX IF NOT EXISTS IX_EducationOrganizationProgramProvider_EducationOrganizationId ON edorgprogram.EducationOrganizationProgramProvider(EducationOrganizationId) INCLUDE (AggregateId);
