CREATE UNIQUE INDEX IF NOT EXISTS UX_e3a1b1_Id ON tx.ActualExt(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_30e8d1_Id ON tx.AsOfStatusALeaver(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_1c17d1_Id ON tx.BudgetExt(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_c6c091_Id ON tx.ContractedInstructionalStaffFTEExt(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_4c1df0_Id ON tx.PayrollExt(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_0acbb2_Id ON tx.SharedServiceArrangementExt(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_67e71e_Id ON tx.SSAOrgAssociationExt(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_a84252_Id ON tx.StudentApplication(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_fcb699_Id ON tx.StudentSpecialEducationProgramEligibilityAssociation(Id);

